---

port: 4000
host: 127.0.0.1
safe: false
future: false

### site serving configuration ###
exclude: [.gitignore]
permalink: /blog/:year/:month/:day/:title.html
timezone: null
lsi: false
markdown: kramdown
#markdown: redcarpet
#redcarpet:
#  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: rouge

### content configuration ###
title:       "mucoder audio tools &amp; plugins"
keywords:    "mucoder vst au tonespace hypercyclic plugin"
description: "mucoder audio tools &amp; plugins"
source_link: "https://github.com/altalogix/mucoder/tree/gh-pages"
favicon:     /img/favicon.ico
touch_icon:  /img/mucodericon128.png
google_analytics_key: UA-17988967-1
disable_cookies: "true"

### template colors, used site-wide via css ###
colors:
  black:     '#444444'
  darkgrey:  '#606060'
#  darkgrey:  '#6D6E71'
#  white:     '#f8f8f8'
  white:     '#EEEEEE'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  grey:      '#EAEAEA'
  contactgreen:    '#63BD2F'
  tonespaceyellow: '#FED700'
  hypercyclicblue: '#6ACDFE'
  kvrblue:         '#3093C7'
  kvrdarkblue:     '#246D91'
  beatdiscoveryred: '#ED2D14'
  beatdiscoveryblue: '#3505D9'
  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      style: "left"

sass:
  style: compressed

# gems:
  #- jekyll-sitemap
  